language: python

python:
  - 3.5
  - 3.6

install:
  - pip install -r requirements.txt

env:
  global:
  - PYPI_USER_NAME: "chaostoolkit"
  - secure: "Z46lWuLoC/tOZKnu8YpKjPvkU9MaOXuW2NJqhsAWOD7TtI0qVwpZL6+3bmGEbmhrO81XDUrGynRMTn//7t54FFEooxpmOYXPpfbjpDPoAhzPj8LLBF+IQIwOVFEYGmgppCdWA5/io7SQJhMpIWO+lw4HC9GLzM00jBurhBldaK8XpQFhaoYYYyZPxdplg4Dk/ynrSMDgeLPyJmg3zmFzNnirxH4LL3Cn9/OHRAwPFwgWPxegRshSLKkIDTsJH3Ej/fVEptxcgzr42fo6Nn48KOeE9uR47t5g3qWoPgau2ZoSDjJPShTemgAyvP2bA3wjewedja+8KPkik/GE5kzHum6TFQGNEfvFmGDc32hNLObI64RAnYZqO3zVNbI565+tOzQZYJ4SPmf2Foct+M+NVoAz+4ttX8xumAkp9e/6yTS8kb342t1+a4eoO/I4iQ37PfkV132blxgdxTQeuNcWaxaLAkNFZMFBzqap7Spypo+0VfQ3iUNaT8dCQ2ZNfLjQlidtnA/Jtr7kbzNuybJEY0Ku7u3HBuzLOuoI7klEeLzLVsFmdckwYcyu8V12MWmBDTZbf8xY7EpuBqCHV1P3yjq1S/a2sqtV/2b7R1Wazt7C12DCeR+7XgymNcMJaTd6MJ9Q4iOuNImPWLlZIz+3dsEyFVbjCx7YBJrQtr6kgxs="
  
script: 
  - bash ci.bash
